server:
  port: 8080

spring:
  application:
    name: dcloud-aipan

  # db
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.134.108.159/dcloud_pan?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  #redis
  data:
    redis:
      host: 8.134.108.159
      port: 6379
      password: 123456

# mybatis-plus??
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: del
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

# minio
minio:
  endpoint: http://8.134.108.159:9000
  access-key: minio_root
  access-secret: minio_123456
  bucket-name: ai-pan
  avatar-bucket-name: avatar

#百炼的key
ai:
  key: sk-4e351b92cab64a8ab5d7e07ce1ed70c4

#模型服务的配置
stream:
  base-url: http://8.134.108.159:8000
  chat-stream-path: /api/chat/stream
  timeout:
    connect: 30s
    response: 5m
    read: 5m
    write: 5m
  pool:
    max-connections: 100
    max-idle-time: 5m
    max-life-time: 10m
    pending-acquire-timeout: 30s
    evict-in-background: 120s