server:
  port: 8080

spring:
  application:
    name: dcloud-aipan

  # 文件上传配置
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

  # db
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_aipan?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  #redis
  data:
    redis:
      host: 8.138.149.225
      port: 6379
      password: redis

# mybatis-plus??
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: del
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

# minio
minio:
  endpoint: http://8.138.149.225:9000
  access-key: vsscfUevOywI2axfotsB
  access-secret: HlG6fh6kfRrhPxm9opXPi5SNyrybkgr9lSeiYoyk
  bucket-name: aipan
  avatar-bucket-name: avatar

#ds的key
ai:
  key: sk-dbaffdea4c3542859392c1dcfbe897fd

#模型服务的配置
stream:
  base-url: http://8.138.149.225:8000
  chat-stream-path: /api/chat/stream
  timeout:
    connect: 30s
    response: 5m
    read: 5m
    write: 5m
  pool:
    max-connections: 100
    max-idle-time: 5m
    max-life-time: 10m
    pending-acquire-timeout: 30s
    evict-in-background: 120s